
services:
  postgres:
    image: postgres:16
    container_name: encomendas-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: encomendas
    ports:
      - "5432:5432"
    volumes:
      - dados_postgres:/var/lib/postgresql/data

volumes:
  dados_postgres: